project:
  type: website

website:
  title: "Otiose Ruminations"
  site-url: "https://otioseruminations.github.io"
  description: "Essays in mathematics, history, and other changing fascinations."
navbar:
  right:
    - text: Mathematics
      href: mathematics.qmd
    - text: All Essays
      href: essays.qmd
    - text: About
      href: about.qmd
  page-footer:
    center: "© 2026 Otiose Ruminations"

format:
  html:
    theme: cosmo
    toc: true
    html-math-method: mathjax
    css: styles.css
